name: Hello World Valcann

on:
  push:
    branches:
      - main
    
jobs:
  echo_hello_World:
    runs-on: ubuntu-latest
    steps:
      - name: Printar Hello World
        run: echo hello world
      - name: Printar Charles atrasado
        run: echo Charles chegou atrasado
