name: Hello World Valcann

on:
  push:
    branches:
      - main
    
jobs:
  echo_hello_World:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, mecos-latest]
    steps:
      - name: Printar Hello World
        run: echo hello world
      - name: Printar Charles atrasado
        run: echo Charles chegou atrasado
